version: "3.7"

services:
  db:
    env_file: words.env
    image: postgres:14
    container_name: db
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  words:
    env_file: words.env
    image: dmitriyvasil1986/words:latest
    container_name: words
    restart: unless-stopped
    volumes:
      - static:/app/backend/static
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - static:/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - words
      - db

volumes:
  static:
    external: false