# Generated by Django 4.2.11 on 2024-05-01 16:21

from django.db import migrations

def set_default_rules_random(apps, schema_editor):
    RulesRandom = apps.get_model('random_generator', 'RulesRandom')

    RulesRandom.objects.create(
        description="поставьте глагол в прошедшее время. [Личное местоимение] [Вспомогательный глагол] [Глагол]",
        name="Глагол в прошедшем времени",
    ).save()

    RulesRandom.objects.create(
        description="поставьте глагол в будущее время. [Личное местоимение] [Вспомогательный глагол] [Глагол]",
        name="Глагол в будущем времени",
    ).save()

def remove_rules_random(apps, schema_editor):
    RulesRandom = apps.get_model('random_generator', 'RulesRandom')
    RulesRandom.objects.filter(name__in=("Глагол в прошедшем времени", "Глагол в будущем времени")).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("random_generator", "0002_auto_20240420_2106"),
        ("verb", "0015_auto_20240501_1546"),
    ]

    operations = [
        migrations.RunPython(set_default_rules_random, remove_rules_random),
    ]
