# Generated by Django 4.1.2 on 2022-10-26 18:31

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Verb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="VerbDeclension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pronoun",
                    models.CharField(
                        choices=[
                            ("ja", main.models.Pronoun["ja"]),
                            ("ti", main.models.Pronoun["ti"]),
                            ("on", main.models.Pronoun["on"]),
                            ("vi", main.models.Pronoun["vi"]),
                            ("mi", main.models.Pronoun["mi"]),
                            ("oni", main.models.Pronoun["oni"]),
                        ],
                        max_length=150,
                    ),
                ),
                ("word", models.CharField(max_length=150)),
                (
                    "verb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verb_declentions",
                        to="main.verb",
                    ),
                ),
            ],
        ),
    ]
