# Generated by Django 4.1.2 on 2022-10-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_pron"),
    ]

    operations = [
        migrations.AddField(
            model_name="verbdeclension",
            name="pron",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verb_declentions",
                to="main.pron",
            ),
            preserve_default=False,
        ),
    ]
