# Generated by Django 4.1.2 on 2022-11-12 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_case_noun_nouncase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(default="f", max_length=150)),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name="noun",
            name="gender",
            field=models.CharField(default="f", max_length=150),
        ),
        migrations.CreateModel(
            name="AdjCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.CharField(max_length=150)),
                ("word", models.CharField(max_length=150)),
                (
                    "adjective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adj_case",
                        to="main.adjective",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adj_case",
                        to="main.case",
                    ),
                ),
            ],
        ),
    ]
