# Generated by Django 4.1.2 on 2022-11-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_adjective_noun_gender_adjcase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adjective",
            name="name",
        ),
        migrations.AddField(
            model_name="adjective",
            name="translate",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adjective",
            name="word",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
