# Generated by Django 4.1.2 on 2022-11-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_adjective_name_adjective_translate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjcase",
            name="gender",
            field=models.CharField(default="f", max_length=150),
        ),
    ]
