# Generated by Django 4.1.2 on 2022-11-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_adjcase_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pronoun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(default="f", max_length=150)),
                ("translate", models.CharField(max_length=150)),
                ("word", models.CharField(max_length=150)),
            ],
        ),
    ]
