# Generated by Django 4.1.2 on 2023-02-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_pronoun"),
    ]

    operations = [
        migrations.CreateModel(
            name="Declentions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.CharField(max_length=150)),
                ("word", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.CharField(max_length=150)),
                ("word", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="NounInfinitive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.CharField(max_length=150)),
                ("word", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="VerbInfinitive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.CharField(max_length=150)),
                ("word", models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name="nouncase",
            name="case",
        ),
        migrations.RemoveField(
            model_name="nouncase",
            name="noun",
        ),
        migrations.RemoveField(
            model_name="verbdeclension",
            name="pron",
        ),
        migrations.RemoveField(
            model_name="verbdeclension",
            name="verb",
        ),
        migrations.AddField(
            model_name="noun",
            name="plural",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pron",
            name="plural",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pronoun",
            name="plural",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="verb",
            name="plural",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="verb",
            name="pron",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verb",
                to="main.pron",
            ),
        ),
        migrations.DeleteModel(
            name="AdjCase",
        ),
        migrations.DeleteModel(
            name="Adjective",
        ),
        migrations.DeleteModel(
            name="Case",
        ),
        migrations.DeleteModel(
            name="NounCase",
        ),
        migrations.DeleteModel(
            name="VerbDeclension",
        ),
        migrations.AddField(
            model_name="noun",
            name="declention",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noun",
                to="main.declentions",
            ),
        ),
        migrations.AddField(
            model_name="noun",
            name="noun",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noun",
                to="main.nouninfinitive",
            ),
        ),
        migrations.AddField(
            model_name="verb",
            name="declention",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verb",
                to="main.declentions",
            ),
        ),
        migrations.AddField(
            model_name="verb",
            name="infinitive",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verb",
                to="main.verbinfinitive",
            ),
        ),
        migrations.AlterField(
            model_name="noun",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noun",
                to="main.gender",
            ),
        ),
        migrations.AlterField(
            model_name="pronoun",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pronoun",
                to="main.gender",
            ),
        ),
    ]
