# Generated by Django 4.1.2 on 2023-02-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_declentions_gender_nouninfinitive_verbinfinitive_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pronoun",
            name="gender",
        ),
    ]
