# Generated by Django 4.1.2 on 2023-02-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_pronoun_gender"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pron",
            new_name="PersonalPronoun",
        ),
        migrations.RenameField(
            model_name="verb",
            old_name="pron",
            new_name="pronoun",
        ),
        migrations.AddField(
            model_name="pronoun",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pronoun",
                to="main.gender",
            ),
        ),
    ]
