# Generated by Django 4.1.2 on 2023-02-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_rename_pron_personalpronoun_rename_pron_verb_pronoun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verbinfinitive",
            name="base",
            field=models.CharField(default="asd", max_length=150),
            preserve_default=False,
        ),
    ]
