# Generated by Django 4.1.2 on 2023-02-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_rename_noun_noun_infinitive"),
    ]

    operations = [
        migrations.AddField(
            model_name="nouninfinitive",
            name="base",
            field=models.CharField(default="asd", max_length=150),
            preserve_default=False,
        ),
    ]
