# Generated by Django 4.1.2 on 2023-02-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_remove_verb_plural"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noun",
            name="gender",
        ),
        migrations.AddField(
            model_name="nouninfinitive",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noun",
                to="main.gender",
            ),
        ),
    ]
