# Generated by Django 4.1.2 on 2023-03-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_pronoun_personal_pronoun"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pronoun",
            name="declentions",
        ),
        migrations.RemoveField(
            model_name="pronoun",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="pronoun",
            name="personal_pronoun",
        ),
        migrations.RemoveField(
            model_name="pronoun",
            name="plural",
        ),
        migrations.RemoveField(
            model_name="verb",
            name="pronoun",
        ),
        migrations.AlterField(
            model_name="pronoun",
            name="translate",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="pronoun",
            name="word",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="PersonalPronoun",
        ),
    ]
