# Generated by Django 4.1.2 on 2023-03-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_remove_verb_infinitive_verb_base_verb_pronoun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pronoun",
            name="been",
            field=models.CharField(default="asd", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pronoun",
            name="personal",
            field=models.CharField(default="asd", max_length=50),
            preserve_default=False,
        ),
    ]
