# Generated by Django 4.1.2 on 2023-04-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_remove_pronoun_been_remove_pronoun_personal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noun",
            name="infinitive",
        ),
        migrations.AddField(
            model_name="noun",
            name="base",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="noun",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noun",
                to="main.gender",
            ),
        ),
        migrations.DeleteModel(
            name="NounInfinitive",
        ),
    ]
