# Generated by Django 4.1.2 on 2023-04-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tags",
            name="translate",
        ),
        migrations.AlterField(
            model_name="tags",
            name="word",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
