# Generated by Django 4.1.2 on 2023-04-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_remove_tags_translate_alter_tags_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="tags",
            name="hidden",
            field=models.BooleanField(default=True),
        ),
    ]
