# Generated by Django 4.2.11 on 2024-04-10 16:04

from django.db import migrations

def insert_pos(apps, schema_editor):
    PartsOfSpeech = apps.get_model('main', 'PartsOfSpeech')
    poss = (
        ("verb", "глагол"),
    )
    for word, translate in poss:
        pos = PartsOfSpeech.objects.create(word=word, translate=translate)
        pos.save()

def remove_pos(apps, schema_editor):
    PartsOfSpeech = apps.get_model('main', 'PartsOfSpeech')
    PartsOfSpeech.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_partsofspeech"),
    ]

    operations = [
        migrations.RunPython(insert_pos, remove_pos),
    ]
