# Generated by Django 4.2.11 on 2024-04-10 16:35

from django.db import migrations

def set_default_pos(apps, schema_editor):
    PartsOfSpeech = apps.get_model('main', 'PartsOfSpeech')
    verb = PartsOfSpeech.objects.get(word='verb')

    Infinitive = apps.get_model('main', 'Infinitive')

    for i in Infinitive.objects.all():
        i.part_of_speech = verb
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_auto_20240410_1604"),
        ("main", "0035_infinitive_part_of_speech"),
    ]

    operations = [
        migrations.RunPython(set_default_pos),
    ]
