# Generated by Django 4.2.11 on 2024-04-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_auto_20240410_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infinitive",
            name="part_of_speech",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="infinitive",
                to="main.partsofspeech",
            ),
        ),
    ]
