# Generated by Django 4.2.11 on 2024-04-28 13:10

from django.db import migrations

def insert_time(apps, schema_editor):
    Time = apps.get_model('main', 'Time')
    Time.objects.create(
        translate="Настоящее",
        word="Present",
    ).save()
    Time.objects.create(
        translate="Будущее",
        word="Future",
    ).save()
    Time.objects.create(
        translate="Прошлое",
        word="Past",
    ).save()

def remove_time(apps, schema_editor):
    Tags = apps.get_model('main', 'Tags')
    Tags.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_infinitivetags"),
    ]

    operations = [
        migrations.RunPython(insert_time, remove_time),
    ]
