# Generated by Django 4.1.2 on 2022-10-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_verb_translate_verbdeclension_translate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pron",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.CharField(max_length=150)),
                ("word", models.CharField(max_length=150)),
            ],
        ),
    ]
