# Generated by Django 4.1.2 on 2022-10-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_verbdeclension_pron"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verbdeclension",
            name="pronoun",
        ),
    ]
