# Generated by Django 4.1.2 on 2023-04-12 05:11

from django.db import migrations, models
import main.support_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Preposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.CharField(max_length=50)),
                ("word", models.CharField(max_length=50)),
            ],
            bases=(
                main.support_mixin.RepresentationClass,
                models.Model,
                main.support_mixin.RandomMixin,
            ),
        ),
    ]
