# Generated by Django 4.1.2 on 2023-04-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preposition", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Preposition",
        ),
    ]
