# Generated by Django 4.1.2 on 2023-04-01 07:32

from django.db import migrations, models
import django.db.models.deletion
import main.support_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0027_remove_pronoun_declentions_remove_verb_pronoun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Noun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.CharField(max_length=150)),
                ("word", models.CharField(max_length=150)),
                ("base", models.CharField(max_length=50, null=True)),
                ("plural", models.BooleanField(default=False)),
                (
                    "declention",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="noun",
                        to="main.declentions",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="noun",
                        to="main.gender",
                    ),
                ),
            ],
            bases=(
                main.support_mixin.RepresentationBaseClass,
                models.Model,
                main.support_mixin.RandomMixin,
            ),
        ),
    ]
