# Generated by Django 4.1.2 on 2023-04-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preposition", "0001_initial"),
        ("noun", "0002_noun_preposition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noun",
            name="preposition",
        ),
        migrations.AddField(
            model_name="noun",
            name="prepositions",
            field=models.ManyToManyField(
                related_name="noun", to="preposition.preposition"
            ),
        ),
    ]
