# Generated by Django 4.1.2 on 2023-04-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preposition", "0001_initial"),
        ("noun", "0005_alter_noun_prepositions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noun",
            name="prepositions",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="noun", to="preposition.preposition"
            ),
        ),
    ]
