# Generated by Django 4.1.2 on 2023-04-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_preposition"),
        ("noun", "0007_alter_noun_prepositions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noun",
            name="prepositions",
            field=models.ManyToManyField(
                blank=True, related_name="noun", to="main.preposition"
            ),
        ),
    ]
