# Generated by Django 4.1.2 on 2023-04-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_tags_hidden"),
        ("noun", "0008_alter_noun_prepositions"),
    ]

    operations = [
        migrations.AddField(
            model_name="noun",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="noun", to="main.tags"
            ),
        ),
    ]
