# Generated by Django 4.1.2 on 2023-04-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("noun", "0009_noun_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noun",
            name="prepositions",
        ),
    ]
