# Generated by Django 4.1.2 on 2023-04-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_tags_hidden"),
        ("verb", "0002_verb_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="verb",
            name="preposition",
            field=models.ManyToManyField(
                blank=True, related_name="verb", to="main.preposition"
            ),
        ),
    ]
