# Generated by Django 4.2.11 on 2024-04-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verb", "0003_verb_preposition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verb",
            name="base",
        ),
        migrations.RemoveField(
            model_name="verb",
            name="preposition",
        ),
        migrations.RemoveField(
            model_name="verb",
            name="pronoun",
        ),
        migrations.RemoveField(
            model_name="verb",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="verb",
            name="time",
        ),
    ]
