# Generated by Django 4.2.11 on 2024-04-10 16:46

from django.db import migrations

def set_default_infinitive(apps, schema_editor):
    Verb = apps.get_model('verb', 'Verb')

    Infinitive = apps.get_model('main', 'Infinitive')
    verb = Infinitive.objects.filter(word='verb').first()

    for v in Verb.objects.all():
        v.infinitive = verb
        v.save()


class Migration(migrations.Migration):

    dependencies = [
        ("verb", "0005_verb_infinitive"),
    ]

    operations = [
        migrations.RunPython(set_default_infinitive),
    ]
