# Generated by Django 4.2.11 on 2024-04-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_alter_infinitive_part_of_speech"),
        ("verb", "0006_auto_20240410_1646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verb",
            name="infinitive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verb",
                to="main.infinitive",
            ),
        ),
    ]
