# Generated by Django 4.2.11 on 2024-04-15 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pronoun", "0004_auto_20240409_1800"),
        ("verb", "0007_alter_verb_infinitive"),
    ]

    operations = [
        migrations.AddField(
            model_name="verb",
            name="personal_pronoun",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verb",
                to="pronoun.personalpronoun",
            ),
        ),
    ]
