# Generated by Django 4.2.11 on 2024-04-15 20:57

from django.db import migrations

def set_default_personal_pronoun(apps, schema_editor):
    Verb = apps.get_model('verb', 'Verb')

    pp = apps.get_model('pronoun', 'PersonalPronoun').objects.first()

    for v in Verb.objects.all():
        v.personal_pronoun = pp
        v.save()

class Migration(migrations.Migration):

    dependencies = [
        ("pronoun", "0004_auto_20240409_1800"),
        ("verb", "0008_verb_personal_pronoun"),
    ]

    operations = [
        migrations.RunPython(set_default_personal_pronoun),
    ]
