# Generated by Django 4.2.11 on 2024-04-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_auto_20240428_1310"),
        ("verb", "0010_alter_verb_personal_pronoun"),
    ]

    operations = [
        migrations.AddField(
            model_name="verb",
            name="time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verb",
                to="main.time",
            ),
        ),
    ]
