# Generated by Django 4.2.11 on 2024-04-28 13:21

from django.db import migrations

def insert_time(apps, schema_editor):
    Verb = apps.get_model('verb', 'Verb')
    Time = apps.get_model('main', 'Time')
    t_present = Time.objects.get(word="Present")
    t_future = Time.objects.get(word="Future")
    t_past = Time.objects.get(word="Past")
    for v in Verb.objects.all():
        v.time = t_present
        v.save()
        Verb(
            personal_pronoun=v.personal_pronoun,
            infinitive=v.infinitive,
            translate=v.translate,
            time=t_past,
            word=v.word,
        ).save()
        Verb(
            personal_pronoun=v.personal_pronoun,
            infinitive=v.infinitive,
            translate=v.translate,
            time=t_future,
            word=v.word,
        ).save()

def remove_time(apps, schema_editor):
    Verb = apps.get_model('verb', 'Verb')
    Time = apps.get_model('main', 'Time')
    t = Time.objects.get(word="Present")
    Verb.objects.exclude(time=t).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("verb", "0011_verb_time"),
    ]

    operations = [
        migrations.RunPython(insert_time, remove_time),
    ]
