# Generated by Django 4.2.11 on 2024-05-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_auto_20240428_1310"),
        ("pronoun", "0004_auto_20240409_1800"),
        ("verb", "0013_alter_verb_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimePersonalPronounVerb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=150)),
                (
                    "personal_pronoun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_verb",
                        to="pronoun.personalpronoun",
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_verb",
                        to="main.time",
                    ),
                ),
            ],
            options={
                "unique_together": {("time", "personal_pronoun")},
            },
        ),
    ]
