# Generated by Django 4.1.2 on 2023-04-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pronoun", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pronoun",
            old_name="declentions",
            new_name="declention",
        ),
    ]
