# Generated by Django 4.2.11 on 2024-04-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pronoun", "0002_rename_declentions_pronoun_declention"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalPronoun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.CharField(max_length=150)),
                ("word", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
